// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NbaShopService.Models
{
    public partial class Cart
    {
        public Cart()
        {
            CustomerBuyDateNavigation = new HashSet<Customer>();
        }

        public int CartId { get; set; }
        public double Price { get; set; }
        public int NumberOfProducts { get; set; }
        public string Products { get; set; }
        public DateOnly Date { get; set; }

        public virtual Customer CustomerCustomerNavigation { get; set; }
        public virtual ICollection<Customer> CustomerBuyDateNavigation { get; set; }
    }
}