// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NbaShopService.Models
{
    public partial class Team
    {
        public int TeamId { get; set; }
        public string Name { get; set; }
        public int Year { get; set; }
        public string HomeAway { get; set; }
        public string Coast { get; set; }
        public string Image { get; set; }
    }
}