// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NbaShopService.Models
{
    public partial class Viewjerseytype
    {
        public string Firstname { get; set; }
        public string LastName { get; set; }
        public DateOnly? BuyDate { get; set; }
    }
}