// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NbaLibrary.Models
{
    public partial class Cart
    {
        public int CartID { get; set; }
        public double Price { get; set; }
        public int NumberOfProducts { get; set; }
        public string Products { get; set; }
        public DateOnly Date { get; set; }
        public int? CustomerID { get; set; }

        public virtual Customer CartNavigation { get; set; }
        public virtual Customer Customer { get; set; }
    }
}