// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NbaLibrary.Models
{
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public string Firstname { get; set; }
        public string LastName { get; set; }
        public DateOnly DateOfBirth { get; set; }
        public string Email { get; set; }
        public string Location { get; set; }
        public int Postcode { get; set; }

        public virtual Cart CustomerNavigation { get; set; }
        public virtual Cart Cart { get; set; }
    }
}