// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NbaLibrary.Models
{
    public partial class Team
    {
        public Team()
        {
            Jersey = new HashSet<Jersey>();
            Shorts = new HashSet<Shorts>();
        }

        public int TeamID { get; set; }
        public string Name { get; set; }
        public int Year { get; set; }
        public string Home { get; set; }
        public string Coast { get; set; }
        public string Image { get; set; }
        public string Away { get; set; }

        public virtual ICollection<Jersey> Jersey { get; set; }
        public virtual ICollection<Shorts> Shorts { get; set; }
    }
}